name: Android Sample

on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: string
        required: true
        default: "ubuntu-22.04"
jobs:
  build:

    runs-on: ${{ inputs.runs-on }}

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - uses: honquyn/debugger-action@main
      name: debugger
      timeout-minutes: 150
      continue-on-error: true
      with:
        ngrok_token: ${{ secrets.NGROK_TOKEN }}
    - name: Complete
      run: pwd
