name: Flutter Tag Build

on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: string
        required: true
        default: "ubuntu-22.04"
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: false
      upload-tag: ${{ github.ref_name }}
